version: '3.3'

services:
  rstudio:
    image: rocker/tidyverse
    environment:
      - USER=${USER}
      - USERID=${USERID}
      - GROUPID=${USERID}
      - PASSWORD=${PASSWORD}
    ports:
      - "7119:8787"
    volumes:
      - /home/${USER}/projects:/home/${USER}/projects
